-- =====================================================================
-- Séance 1 : Missions M1 à M6
-- =====================================================================
SET client_encoding = 'UTF8';

-- M1.2 & M1.3 : Création des listes
CREATE TABLE listes (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id INTEGER NOT NULL REFERENCES utilisateurs(id) ON DELETE CASCADE,
    titre          VARCHAR(100) NOT NULL,
    est_publique   BOOLEAN NOT NULL DEFAULT FALSE,
    cree_le        DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE liste_films (
    liste_id INTEGER NOT NULL REFERENCES listes(id) ON DELETE CASCADE,
    film_id  INTEGER NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    position INTEGER NOT NULL CHECK (position > 0),
    PRIMARY KEY (liste_id, film_id),
    UNIQUE (liste_id, position)
);

-- M1.4 : Le top Nolan
INSERT INTO listes (utilisateur_id, titre, est_publique)
SELECT id, 'Mon top Nolan', TRUE FROM utilisateurs WHERE pseudo = 'nolanfan';

INSERT INTO liste_films (liste_id, film_id, position)
SELECT l.id, f.id, v.pos
FROM listes l
CROSS JOIN (VALUES ('The Dark Knight', 1), ('Inception', 2), ('Batman Begins', 3)) AS v(titre, pos)
JOIN films f ON f.titre = v.titre
WHERE l.titre = 'Mon top Nolan';

-- Les requêtes de sélection (M2 à M6) pour validation par le prof
-- M2.1 : Les années 2000
SELECT titre, annee, genre FROM films WHERE annee BETWEEN 2000 AND 2010 ORDER BY annee ASC, titre ASC;

-- M2.2 : La filmographie de Kevin Bacon
SELECT f.titre, f.annee FROM films f
JOIN casting c ON c.film_id = f.id
JOIN personnes p ON p.id = c.personne_id
WHERE p.nom = 'Kevin Bacon' AND c.role = 'acteur' ORDER BY f.annee ASC;

-- M2.4 : Les mieux notés
SELECT f.titre, ROUND(AVG(n.note), 2) AS moyenne, COUNT(n.note) AS nb_notes
FROM films f JOIN notes n ON n.film_id = f.id
GROUP BY f.id, f.titre HAVING COUNT(n.note) >= 5
ORDER BY moyenne DESC, nb_notes DESC LIMIT 5;

-- M4.3 : Le nombre de Kevin Bacon (Récursif)
WITH RECURSIVE bacon_graph AS (
    SELECT c.personne_id, 1 AS distance FROM casting c JOIN personnes p ON p.id = c.personne_id WHERE p.nom = 'Kevin Bacon' AND c.role = 'acteur'
    UNION
    SELECT c2.personne_id, bg.distance + 1 FROM bacon_graph bg JOIN casting c1 ON c1.personne_id = bg.personne_id AND c1.role = 'acteur' JOIN casting c2 ON c2.film_id = c1.film_id AND c2.role = 'acteur' WHERE bg.distance < 4
),
distances AS (SELECT personne_id, MIN(distance) - 1 AS nombre_de_bacon FROM bacon_graph GROUP BY personne_id)
SELECT p.nom, d.nombre_de_bacon FROM distances d JOIN personnes p ON p.id = d.personne_id WHERE d.nombre_de_bacon > 0 ORDER BY d.nombre_de_bacon DESC, p.nom ASC;